server:
  port: 8989
  servlet:
    #设置访问url前缀
    context-path: /api

jasypt:
  #对数据库连接串加密的方法
  encryptor:
    # 你的秘钥
    password: sicnu

logging:
  #配置日志配置文件地方
  config: classpath:logback_spring.xml
  level:
    #开启sql打印
    com.sicnu.boot.mapper: debug

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #对数据库连接串加密
      url: ENC(y7VIwY2A4BCPayCZE2kZqS1F4arB7igrmHeQ96CHzh3eYrtjOGz0upinU3FhcA0zBeOCSIoY/baMPYnmoZ2DZtDwBAHDij3wTVpEcMqTre8SB9RMt39X650ShMwysCHv)
      username: ENC(r5A15Jti3Re6N0Zl0xtVzQ==)
      password: ENC(8qqyb8ZlnsJqv82c4f0aUA==)
  #配置redis
  redis:
    #配置主机号
    host: 127.0.0.1
    #配置端口号
    port: 6379
    #配置密码 默认不设置密码
#    password: 123456
    #配置数据库索引（默认为0）
    database: 1
    client-type: jedis
    jedis:
      pool:
        #连接池对打阻塞等待时间（负表示没有限制）
        max-wait: 10000
        #连接池最大连接数(负表示没有限制)
        max-active: 100
        #连接池中的最大空闲链接
        max-idle: 20
        #连接池中的最小空闲链接
        min-idle: 0
    #链接超时时间
    timeout: 3000
  jackson:
    #设置时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.sicnu.boot.pojo
  configuration:
    # 数据库自动驼峰转换 user-name 对应 userName
    map-underscore-to-camel-case: true
    # spring boot集成mybatis的方式打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper文件地址
  mapper-locations: classpath:mapper/*Mapper.xml

# 配置pagehelper的属性
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#配置Oss
oss-config:
  accessId: 1
  accessKey: 1
  endpoint: 1
  bucket: 1
  host: https://${oss-config.bucket}.${oss-config.endpoint}

# 腾讯云短信服务配置
sms-config:
  # 腾讯云账户密钥对 secretId 和 secretKey
  secretId: AKIDa2HGzThfMn093g3FBrJXXMxjIcgW8UbU
  secretKey: oOjpgIdiX9XhcKo33oKbdQxEFzThfMny
  # 短信应用appId和appKey
  appId: 1400736359
  appKey: ed61c0223c636591f657b06cf19cdd5e
  # 签名
  smsSign: 仰望星空探索宇宙公众号
  # 过期时间
  expireTime: 5  # 5min
  # redis存储前缀
  phonePrefix: pinganky_sms
  # 模板id
  templateIds:
    code: 1540491