server:
  port: 8989

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/computer-system?serverTimezone=UTC
      username: root
      password: 123456

mybatis:
  type-aliases-package: com.sicnu.boot.pojo
  configuration:
    # ????uName?????u_name
    map-underscore-to-camel-case: true
  #mapper??????
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com.sicnu.boot.mapper: debug